### PR TITLE
fix the breaking change for dynamic/functionNode

### PR DESCRIPTION
**Pull request by yutkat**
https://github.com/L3MON4D3/LuaSnip/issues/81#issuecomment-1064891636

### CODE REVIEW

**Comment by molleweide** [comment]
Thanks for submitting! I am going to have a look at this later :)

**Comment by yutkat** [comment]
@molleweide What's going on with this one?

**Comment by molleweide** [comment]
Hey man! I merged it in just now :)

**Comment by yutkat** [comment]
Thanks!

**Pull request merged**
